version: "#{build}"
os: Visual Studio 2015
configuration: Release

before_build:
- ps: dotnet --info
- ps: dotnet restore --verbosity detailed

test_script:
- ps: dotnet test -c $env:CONFIGURATION ./test/Yargon.LanguageServer.Tests

after_test:
- ps: dotnet pack -c $env:CONFIGURATION src/Yargon.LanguageServer/

artifacts:
- path: 'src/Yargon.LanguageServer/bin/Release/*.nupkg'
  name: NuGet Packages

deploy:
- provider: GitHub
  description: ""
  auth_token:
    secure: gxD+NTodnQNMMljEkLwbmfQdsyBZFRIioVMM+RQSFD3+h1GEgsEGuINxcfNgVceY
  artifact: /.*\.nupkg/
  draft: true
  prerelease: true
  on:
    branch: master
    appveyor_repo_tag: true
- provider: NuGet
  api_key:
    secure: 80Ifo8pBjEsFrG2mn50qSl7+uFgquQSareLS3l21DfWT49nFtb/SZsHSkR/DRDsO
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: master
    appveyor_repo_tag: true
